name: Git Vertag
author: kyoh86
description: Put new git tag for next semantic version
branding:
  icon: at-sign
  color: gray-dark

inputs:
  method:
    description: |
      Which number to increment in the semantic versioning.
      Set 'major', 'minor', 'patch' or 'get'.
    required: true
  push:
    description: |
      If the new tag should be pushed, set "true".
    required: false
    default: 'false'
outputs:
  vertag:
    description: New tag with semantic version
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.method }}
    - ${{ inputs.push }}
